default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root

development:
  <<: *default
  database: bowling_score_development

production:
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  password: root
  database: bowling_score_production